physiology:
  weight_kg: 70.0
  V_blood: 5.0
  V_liver: 1.8
  Q_liver: 90.0
  V_muscle: 29.0
  Q_muscle: 450.0
  V_fat: 18.0
  Q_fat: 30.0
  CLint_liver: 20.0

compound:
  name: DrugX
  Kp_liver: 8.0
  Kp_muscle: 2.5
  Kp_fat: 40.0
  k_abs: 0.8

qsp:
  kon: 0.001
  koff: 0.1
  Rtot: 100.0
  kprod: 0.5
  kdeg: 0.1

dosing:
  - type: iv_bolus
    amount: 50.0
    time: 0.0
    duration: 0.0
  - type: oral
    amount: 100.0
    time: 8.0
    duration: 0.0